### ISSUE TITLE
Unable to make pivot component's height 100%

### ISSUE THREAD

**Issue by ezk84** [flexmonster/ng-flexmonster#4]
I am developing a full height app, and when setting the [height] input to '100%' the component renders with a height of about 200px or so, whereas I would expect it to have a height equal to its parent component. 

When using the pain javascript pivot, I have sometimes gotten it to fill the whole height of its parent by using flexbox and not specifying a height in the initialization, but neither of these work.

Here's an example of what that looks like using the js component:
https://jsfiddle.net/sn4xk5qa/1/ (be sure to make the output frame higher by dragging the top)

**Comment by tsshn** [comment]
Hello,

Thank you for reaching out to us.

It seems the problem is not reproducible on the provided example.
Our team suggests making sure that the parent element of the Flexmonster container takes the full height of the window.
If it does not work, please provide us with an example where the issue would be reproducible.

We are looking forward to hearing from you.

Regards,
Illia

**Comment by ezk84** [comment]
Hey there,
Here's an example using the ng-flexmonster module (I posted the non-angular example before not as a test case, but as an example of where it does work):
[fmtest.zip](https://github.com/flexmonster/ng-flexmonster/files/4749017/fmtest.zip)

So, out of the box settings [height]="'100%'" does not work.

I got it to work after adding the following CSS in my component, to make sure the parent of the pivot table (which is a div inside the FlexmonsterPivot component) has height: 100%:

```css
fm-pivot ::ng-deep > div {
    height: 500px;
    min-height: 100%;
}
```

**Comment by tsshn** [comment]
Hello,

Thank you for your feedback and for providing an example.

We are happy to hear you have found a way to achieve the desired result.

Concerning the reason for the described behavior, our team would like to kindly explain that the height can not be defined in percents in case the parental div of Flexmonster container is <body>.

It is applicable to any HTML element due to the fact that the percentage is calculated with respect to the height of the generated box's containing block. If the height of the containing block is not specified explicitly (i.e., it depends on content height), and this element is not absolutely positioned, the value computes to auto.

Please let us know in case any additional assistance is needed.

Regards
